# Adds namespace to all resources.
namespace: capt-system
# Value of this field is prepended to the
# names of all resources, e.g. a deployment named
# "wordpress" becomes "alices-wordpress".
# Note that it should also match with the prefix (text before '-') of the namespace
# field above.
namePrefix: capt-
# Labels to add to all resources and selectors.
commonLabels:
  cluster.x-k8s.io/provider: infrastructure-tinkerbell
resources:
- ../crd
- ../rbac
- ../namespace
