# Value of this field is prepended to the
# names of all resources, e.g. a deployment named
# "wordpress" becomes "alices-wordpress".
# Note that it should also match with the prefix (text before '-') of the namespace
# field above.
namePrefix: capt-
# Labels to add to all resources and selectors.
commonLabels:
  cluster.x-k8s.io/provider: infrastructure-tinkerbell
bases:
- crd
#- webhook # Disable this if you're not using the webhook functionality.
- default
images:
- name: quay.io/tinkerbell/cluster-api-provider-tinkerbell:e2e # images with this name
  newTag: v0.0.0-dirty # {"type":"string","x-kustomize":{"setter":{"name":"image-tag","value":"v0.0.0-dirty"}}}
  newName: quay.io/tinkerbell/cluster-api-provider-tinkerbell # and this name
