name: CI
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    container: golangci/golangci-lint:v1.32.2
    timeout-minutes: 10
    steps:

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Run lint
        run: make lint
