name: CI
on:
  pull_request:
  push:
    branches:
      - main

env:
  CGO_ENABLED: 0
  GO_VERSION: '1.21'

jobs:
  validate:
    name: "Validate ${{ matrix.target }}"
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        target: ["verify", "lint", "test"]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v4
        with:
          go-version: "${{ env.GO_VERSION }}"
          cache: true

      - uses: actions/cache@v3
        with:
          path: hack/tools/bin
          key: ${{ runner.os }}-tools-bin-${{ matrix.target }}-${{ hashFiles('Makefile') }}
          restore-keys: |
            ${{ runner.os }}-tools-bin-${{ matrix.target }}-
            ${{ runner.os }}-tools-bin-

      - uses: actions/cache@v3
        if: ${{ matrix.target == 'test' }}
        with:
          path: /tmp/kubebuilder-tools-*.tar.gz
          key: ${{ runner.os }}-tmp-${{ matrix.target }}-${{ hashFiles('scripts/fetch_ext_bins.sh') }}
          restore-keys: |
            ${{ runner.os }}-tmp-${{ matrix.target }}-
            ${{ runner.os }}-tmp-

      - name: ${{ matrix.target }}
        run: make ${{ matrix.target }}

  codespell:
    name: Codespell
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Codespell
        uses: codespell-project/actions-codespell@v2.0
        with:
          check_filenames: true
          check_hidden: true
          skip: "./.git,./go.mod,./go.sum"
          ignore_words_list: ro
