name: CI
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  validate:
    name: "Validate ${{ matrix.target }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target: ["verify", "lint", "test"]
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - uses: ./.github/actions/setup-go
      - uses: actions/cache@v3
        with:
          path: hack/tools/bin
          key: ${{ runner.os }}-tools-bin-${{ matrix.target }}-${{ hashFiles('Makefile') }}
          restore-keys: |
            ${{ runner.os }}-tools-bin-${{ matrix.target }}-
            ${{ runner.os }}-tools-bin-
      - uses: actions/cache@v3
        if: ${{ matrix.target == 'test' }}
        with:
          path: /tmp/kubebuilder-tools-*.tar.gz
          key: ${{ runner.os }}-tmp-${{ matrix.target }}-${{ hashFiles('scripts/fetch_ext_bins.sh') }}
          restore-keys: |
            ${{ runner.os }}-tmp-${{ matrix.target }}-
            ${{ runner.os }}-tmp-
      - name: ${{ matrix.target }}
        run: make ${{ matrix.target }}
  codespell:
    name: Codespell
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Codespell
        uses: codespell-project/actions-codespell@v1.0
        with:
          check_filenames: true
          check_hidden: true
          skip: "./.git,./go.mod,./go.sum"
          ignore_words_list: ro
